---
- name: CLI | Ensure jenkins has started securely
  get_url:
    url: "http://{{ jenkins_cli_user }}:{{ jenkins_cli_pass }}@127.0.0.1:8080/cli/"
    dest: /dev/null
    validate_certs: no
  register: secure_jenkins_result
  until: secure_jenkins_result.msg.find("200 OK") != -1
  retries: "8"
  delay: "15"
  changed_when: false
  when: jenkins_install|changed and jenkins_cli_user is defined and jenkins_cli_pass is defined
  tags:
    - install
    - jenkins

- name: CLI | Ensure jenkins has started
  get_url:
    url: http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar
    dest: /dev/null
    validate_certs: no
  register: jenkins_result
  until: jenkins_result.msg.find("200 OK") != -1
  retries: "8"
  delay: "15"
  changed_when: false
  when: jenkins_install|changed and jenkins_cli_user is not defined and jenkins_cli_pass is not defined
  tags:
    - install
    - jenkins

# Create Jenkins CLI destination directory
- name: "create jenkins cli destination directory"
  file:
    path: "{{ jenkins_cli_destination }}"
    state: directory
  tags:
    - package
    - jenkins

# Get Jenkins CLI from localhost
- name: CLI | Ensure jar is installed
  get_url:
    url: "http://{{ jenkins_cli_user }}:{{ jenkins_cli_pass }}@127.0.0.1:8080/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_cli_destination }}/"
    owner: jenkins
    mode: 0440
  when: jenkins_cli_user is defined and jenkins_cli_pass is defined
  tags:
    - package
    - jenkins

- name: get Jenkins cli
  get_url:
    url: http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar
    dest: "{{ jenkins_cli_destination }}/"
    owner: jenkins
    mode: 0440
  become: yes
  become_user: jenkins
  when: jenkins_cli_user is not defined and jenkins_cli_pass is not defined
  tags:
    - package
    - jenkins

# Set up jenkins-cli executable script
- name: create jenkins-cli executable script
  template:
    dest: /usr/bin/jenkins-cli
    src: jenkins-cli.j2
    mode: 0755
  tags:
    - package
    - jenkins

- name: "create jenkins cli configuration directory"
  file:
    path: /etc/jenkins
    state: directory
  tags:
    - package
    - jenkins

- name: create jenkins-cli configuration
  copy:
    dest: /etc/jenkins/cli.conf
    src: cli.conf
    mode: 0644
  tags:
    - package
    - jenkins
