---
# If Jenkins is installed or updated, wait for pulling the Jenkins CLI,
# assuming 60s should be sufficiant
- name: secure wait for jenkins to start
  wait_for:
    host: "{{ jenkins_secure_id }}:{{ jenkins_secure_api }}@localhost"
    delay: 600
    port: 8080
    search_regex: "(>Build History<)"
  when: jenkins_install|changed and jenkins_secure_id is defined and jenkins_secure_api is defined
  tags:
    - install
    - jenkins

- name: wait for jenkins to start
  wait_for:
    delay: 600
    port: 8080
    search_regex: "(>Build History<)"
  when: jenkins_install|changed and jenkins_secure_id is not defined and jenkins_secure_api is not defined
  tags:
    - install
    - jenkins

# Create Jenkins CLI destination directory
- name: "create jenkins cli destination directory"
  file:
    path={{ jenkins_cli_destination }}
    state=directory
  tags:
    - package
    - jenkins

# Get Jenkins CLI from localhost
- name: get Jenkins cli
  get_url:
    url=http://localhost:8080/jnlpJars/jenkins-cli.jar
    dest={{ jenkins_cli_destination }}
    owner=jenkins
    mode=0440
  tags:
    - package
    - jenkins

# Set up jenkins-cli executable script
- name: create jenkins-cli executable script
  template:
    dest=/usr/bin/jenkins-cli
    src=jenkins-cli.j2
    mode=0755
  tags:
    - package
    - jenkins

- name: "create jenkins cli configuration directory"
  file:
    path=/etc/jenkins
    state=directory
  tags:
    - package
    - jenkins

- name: create jenkins-cli configuration
  copy:
    dest=/etc/jenkins/cli.conf
    src=cli.conf
    mode=0644
  tags:
    - package
    - jenkins
