---
# Install repository
- include: repository.yml
# Install server
- include: install.yml
# Set up (user) and group
- include: user.yml
# Install cli
- include: cli.yml
# Install/Update plugins
- include: plugins.yml
  when: jenkins_plugins|length > 0
# authentication
- include: ldap.yml
  when: jenkins_ldap == True

# credentials
- include: ssh.yml
  when: jenkins_generate_ssh == True
