---
# Install repository
- include: repository.yml
# Install server
- include: install.yml
# Set up (user) and group
- include: user.yml
# Install cli
- include: cli.yml
# Update the installation
- include: update.yml
# Install plugins
- include: plugins.yml
  when: jenkins_plugins|length > 0
# credentials
- include: ssh.yml
# git repository support
- include: bitbucket.yml
