---
# Ubuntu LTS 12.04 version is out of date, therefore the updating to use
# http://pkg.jenkins-ci.org/debian/

# Add Jenkins repository key
- name: Add jenkins apt-key
  apt_key:
    url: http://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  sudo: yes

# Add Jenkins repository
- name: Add Jenkins repository
  apt_repository:
    repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
    state: present
  sudo: yes
