---
# Get latest Jenkins update file
- name: get jenkins updates information
  get_url:
    url=http://updates.jenkins-ci.org/update-center.json
    dest=/tmp/jenkins-update-center.json
    force=yes
  register: jenkins_updates_download
  tags:
    - update
    - jenkins

- name: ensure curl is installed to upload information
  apt:
    pkg=curl
    state=present
  when: jenkins_updates_download.changed
  tags:
    - update
    - jenkins

# Jenkins Update-center
- name: ensure jenkins has the latest information
  shell: "cat /tmp/jenkins-update-center.json | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:8080/updateCenter/byId/default/postBack"
  when: jenkins_updates_download.changed
  notify:
    - restart jenkins
  tags:
    - update
    - jenkins
